---
variables:
  LEKTOR_BUILD_FLAGS: scss
  SITE_URL: styleguide.torproject.org
  STAGING_URL: styleguide.staging.torproject.net

include:
  - project: tpo/tpa/ci-templates
    file:
      - lektor.yml
      - static-shim-deploy.yml
